config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'animals#index'
	resources :animals, only: [:index, :show] do
		resources :fosters, only: [:new, :create]
	end
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foster.rb
class Foster < ApplicationRecord
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find(params[:id])
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.fetch(:animal, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fosters_controller.rb
class FostersController < ApplicationController
  # GET /fosters/new
  def new
    @foster = Foster.new
  end

  # POST /fosters
  def create
    Foster.create(foster_params)
    animal = Animal.find(foster_params[:animal_id])
    animal.update(adopted: true)
    redirect_to root_path, notice: "#{animal.name} adotado com sucesso"
  end

  private

  def foster_params
    params.permit(:name, :age, :address, :pets, :children, :animal_id)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fosters_helper.rb
module FostersHelper
end

app/views/animals/_form.html.erb
<%= form_for(animal) do |f| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= link_to image_tag(animal.photo, style: 'height:300px;width:300px;',class: "img-circle img-responsive"), animal %></td>
        <td><b><%= "adotado!" if animal.adopted %></b></td>
        <td><%= animal.name %></td>
        <td><%= animal.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<%= image_tag(@animal.photo, size: "500x300") %>

<h2>Conheça o <%= @animal.name %>!</h2>

<p><%= @animal.description %></p>

<%= link_to('Quero adotar!', new_animal_foster_path(@animal.id)) %>

app/views/fosters/_form.html.erb
<%= form_for(foster) do |f| %>
  <% if foster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foster.errors.count, "error") %> prohibited this foster from being saved:</h2>

      <ul>
      <% foster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fosters/edit.html.erb
<h1>Editing Foster</h1>

<%= render 'form', foster: @foster %>

<%= link_to 'Show', @foster %> |
<%= link_to 'Back', fosters_path %>

app/views/fosters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fosters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fosters.each do |foster| %>
      <tr>
        <td><%= link_to 'Show', foster %></td>
        <td><%= link_to 'Edit', edit_foster_path(foster) %></td>
        <td><%= link_to 'Destroy', foster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foster', new_foster_path %>

app/views/fosters/new.html.erb
O, aqui é página de formulário

<%= form_tag(controller: 'fosters', action: 'create') do %>
	<%= label_tag('Nome:') %>
	<%= text_field_tag(:name) %>
	<%= label_tag('Idade:') %>
	<%= number_field_tag(:age) %>
	<%= label_tag('Endereço:') %>
	<%= text_field_tag(:address) %>
	<%= label_tag('Você tem outros animais?') %>
	<%= check_box_tag(:pets) %>
	<%= label_tag('Você tem filhos?') %>
	<%= check_box_tag(:children) %>
	<%= submit_tag('Enviar') %>
<% end %>

app/views/fosters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_foster_path(@foster) %> |
<%= link_to 'Back', fosters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoteUmAmigo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>